[profile.default]
src = "src"
optimizer = true
optimizer_runs = 200
out = "out"
evm_version = "cancun"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
